# Generated by Django 5.1.1 on 2024-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptioncache',
            name='transcription',
        ),
        migrations.AddField(
            model_name='transcriptioncache',
            name='transcription_data',
            field=models.JSONField(default=dict),
        ),
    ]
